### ISSUE TITLE
When will be confirmed?

### ISSUE THREAD

**Issue by d4mn** [NativeScript/nativescript-geolocation#1]
When this module be confirmed and allowed to be tested in companion app? Or maybe there is a way to test it without building actual app?

**Comment by hshristov** [comment]
@d4mn If there is enough demand we will consider adding it to companion app.
Still you can use it in your own app.

**Comment by dtopuzov** [comment]
Companion app is part of Telerik AppBuilder paid offering, so it should addressed to them via their support channels.
