### ISSUE TITLE
enableLocationRequest function does nothing when called on iOS 9.3.1

### ISSUE THREAD

**Issue by okmttdhr** [NativeScript/nativescript-geolocation#10]
enableLocationRequest function does nothing when called on iOS 9.3.1.
I got the error like below, when I run `tns deploy ios`;

```
nativescript-geolocation 1.7.1 for ios is not compatible with the currently installed framework version 1.7.0.
```

How can I fix this?

**Comment by okmttdhr** [comment]
I found the problem here.

https://github.com/NativeScript/nativescript-geolocation/blob/master/source/nativescript-geolocation.ios.ts#L169

In this case, `platformModule.device.osVersion` was `9.3.1`, so `Number(platformModule.device.osVersion)` returns `NaN`.

It works fine when I comment `if (Number(platformModule.device.osVersion) >= 8.0) {` out.

**Comment by hshristov** [comment]
@okmttdhr Fixed in master branch. Please try with it and write back.
