### ISSUE TITLE
Nativescript-geolocation Error in Anguler

### ISSUE THREAD

**Issue by arunanamal** [NativeScript/nativescript-geolocation#110]
Hi,
I added Nativescript-geolocation plugin in to angular app, and import relevant modules as per the document.
but it gives below error

```
JS: ERROR Error: The module AppModule was bootstrapped, but it does not declare
"@NgModule.bootstrap" components nor a "ngDoBootstrap" method. Please define one
 of these.
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: The module AppModule was bootstrapped, but it does not declare
"@NgModule.bootstrap" components nor a "ngDoBootstrap" method. Please define one
 of these.
```

Appreciate your help to rectify above issue

Thanks 
Namal

**Comment by arunanamal** [comment]
Hi,
Any sample Nativescript-geolocation plugin with anguler

Thanks

**Comment by DimitarTachev** [comment]
Hi @arunanamal,

The plugin does not have any angular specific logic and it should work in the same way as its shown in the Demo app. In general, you just need to require the plugin in your components and use its methods when needed.

Unfortunately, we don't have any Angular specific code snippets or a Demo application. The above-mentioned exception looks like some general problem with bootstrapping an Angular app but we will keep this issue opened as its a very good idea to have an Angular demo along with the typescript one.

I will also mark it with the `Help wanted` label as its a good issue for an external contribution.

**Comment by elena-p** [comment]
There is already a [demo-angular](https://github.com/NativeScript/nativescript-geolocation/tree/master/demo-angular) app in the repo.
