### ISSUE TITLE
Check for mock location

### ISSUE THREAD

**Issue by anurag0707** [NativeScript/nativescript-geolocation#111]
Do you have any provision to check whether the location is coming from a mock provider or not

**Comment by lini** [comment]
There is a method available for Android 4.3 and higher called [.isFromMockProvider()](https://developer.android.com/reference/android/location/Location.html#isFromMockProvider()). Here is how to use it with the `nativescript-geolocation` plugin:

```JavaScript
geolocation.getCurrentLocation({
    desiredAccuracy: Accuracy.high,
    maximumAge: 5000,
    timeout: 10000
}).then(function (loc) {
    // check if mock location (Android API level >=18)
    if (loc.android && loc.android.isFromMockProvider()) {
    }
}, function (e) {
    console.log("Error: " + (e.message || e));
});
```
