### ISSUE TITLE
Get distance between current location and markers on map?

### ISSUE THREAD

**Issue by NikicaAsanin** [NativeScript/nativescript-geolocation#125]
I have users current location on map and big number of markers. I would like to trigger when user is close to some of markers(for example if users is 200 m from marker, show him alert). Any ideas on solving this issue or any cool suggestion on my problem? 

App - NativeScript  + Angular

**Comment by NickIliev** [comment]
@NikicaAsanin I guess a possible approach would be to use `watchLocation` to check for location changes and calculate the distance between the markers and the current location at this point.

[There are a number of threads](https://www.google.bg/search?rlz=1C1CHBF_enBG781BG781&ei=gjbDWpuMBYPa6ASI5buAAg&q=distance+between+location+and+markers+Android+java&oq=distance+between+location+and+markers+Android+java&gs_l=psy-ab.3..33i160k1l2.3949.5117.0.5203.12.10.0.0.0.0.158.841.1j6.7.0....0...1c.1.64.psy-ab..5.5.607...33i21k1j33i22i29i30k1.0.XVsc5ylR6LA) showing how to calculate the distance between markers (and/or location) in Android and they should be applicable for your scenario (of course the code should be written by using JS/TS and the nativescript-geolocation properties)

Please post how-to related questions in the community channels where the NativeScript community can help you with solutions ([NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general))
