### ISSUE TITLE
GPS location services time out issue

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-geolocation#126]
_From @dbay920 on April 16, 2018 18:23_

**GPS location services time out issue: Upon first run of app, location services are blocked until you allow app to use your location data. After you click allow, however, the service seems to be timed out and won't work until app is re-started. This seems to only be a problem on the home view.**

### Which platform(s) does your issue occur on?
**Both**

### Please provide the following version numbers that your issue occurs with:
- CLI: **3.4.3**
- Cross-platform modules: **3.4.1**
- Runtime(s): **Android: 3.4.2   iOS: 3.4.1**
- Plugin(s): "**nativescript-geolocation": "^3.0.0"    "nativescript-locate-address": "^1.0.2"**

### Please tell us how to recreate the issue in as much detail as possible.
**Occurs upon first launch after install, github repo here: https://github.com/dbay920/phn-app/tree/master/MyPHN**

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem. 
**I would imagine something to do with my app's [home.component.ts file](https://github.com/dbay920/phn-app/edit/master/MyPHN/app/home/home.component.ts)**

_Copied from original issue: NativeScript/NativeScript#5691_

**Comment by elimin8r** [comment]
#91 seems to be the underlying issue. i cannot get the promise to resolve or reject.

**Comment by dbay920** [comment]
Getting the following error when I run app with log trace:

```
JS: Error: Location service is not enabled or using it is not granted.
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'image' of undefined
JS: TypeError: Cannot set property 'image' of undefined
```

**Comment by VladimirAmiorkov** [comment]
Hi @dbay920 @elimin8r ,

I see that your project is using the 3.0.0 version of nativescript-geolocation, I managed to observe the issue in your project with that version. The good news is that with our latest version "4.2.6" the described issue is resolved. Simply upgrade your project to the latest version by changing your package.json to:
`nativescript-geolocation: "4.2.6"`

I will close this issue, if you continue to experience such issues do let me know.

**Comment by dbay920** [comment]
Updating to 4.2.6 worked, but I had to first manually delete existing nativescript-geolocation directory from node_modules in order for it to install correct version. Thanks for your help!
