### ISSUE TITLE
Android build fails after adding nativescript-geolocation plugin

### ISSUE THREAD

**Issue by johny8228** [NativeScript/nativescript-geolocation#129]
Hi,

After adding nativescript-geolocation plugin to my project the build is failing for Android.
The issue happens in platforms\android\build.gradle at this line :
"def oldProductFlavorsText = content.substring(indexStart, indexEnd + 1);"

The error is String index out of range -1.
What am I doing wrong?

Thanks,
Ionut

**Comment by zbranzov** [comment]
Hi @johny8228,
Would you fill the new issues form as all information asked there would help us investigate further?
Additionally, I wonder whether you can reproduce the issue using plugin's demo apps or we have to use one provided by you.

**Comment by omertokmak92** [comment]
Hello, i faced same issue. i opened node_modules->nativescript-geolocation->platforms->android->include.gradle. Then i changed include.gradle like this;

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

android {
	productFlavors {
		"nativescript-geolocation" {
			dimension "nativescript-geolocation"
		}
	}
}

dependencies {
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : "11.4.0"
	compile "com.google.android.gms:play-services-location:$googlePlayServicesVersion"
}

In original there is no productFlavors in android { }  and it goes to error. i hope it will help.

**Comment by upetri** [comment]
Hi, this is still an issue. If you install nativescript-geolocation v4.3.0 via npm it's `include.gradle` looks like this:
```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

android {
	
}

dependencies {
    def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : "11.4.0"
    compile "com.google.android.gms:play-services-location:$googlePlayServicesVersion"
}
```
And therefore the error occurs that @johny8228 mentions. 
When I downgrade to 4.2.4 it works fine because `productFlavors` is declared:
```
...
android {
    productFlavors {
        "nativescript-geolocation" {
	    dimension "nativescript-geolocation"
	}
    }
}
...
```
My guess is that your `.npmignore` file has an error. It contains:
```
...
/platforms/android/**/*
!platforms/android/include.gradle
...
```
It looks like the guy who wrote this wanted to not ignore `include.gradle` but the `/**/*` didn't match that gradle file so the `!` maybe resulted in the `include.gradle` file being ignored.
