### ISSUE TITLE
Android Wear - enableLocationRequest() throws ApiException 10:

### ISSUE THREAD

**Issue by ThomasJFR** [NativeScript/nativescript-geolocation#130]
### Which platform(s) does your issue occur on?
- iOS/Android/Both: Android
- iOS/Android versions: Android 7.1.1, Wear OS 2.1.1
- emulator or device. What type of device? Device, Polar M600 Smartwatch.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0
- Cross-platform modules: 3.1.1
- Runtime(s): tns-android 4.0.1
- Plugin(s):
<details><summary> Plugins</summary>
<pre><code>
 "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-bluetooth": "^1.2.0",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-permissions": "^1.2.3",
    "nativescript-snackbar": "^3.0.0",
    "nativescript-texttospeech": "^2.0.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "nativescript-vibrate": "^1.1.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "~1.5.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-worker-loader": "^0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.2.1",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
</code></pre>
</details>

### Please, tell us how to recreate the issue in as much detail as possible. 
Using the Polar M600 (which has an onboard GPS), running the enableLocationRequest() method results in an error:

`ApiException 10: Not implemented on this platform`

I've outlined a step-by-step process for reproducing the problem in the section below.

### Is there any code involved? 

Create a default angular app, install the plugin:
`>> tns create WearTest --template angular`
`>> cd WearTest`
`>> tns plugin add nativescript-geolocation`

In *items.components.ts*, add the following import:
`import * as Location from "nativescript-geolocation";`
Add the following code inside `ngOnInit()`
`Location.enableLocationRequest()`

Now, add the android platform, then run the app:
`>> tns platform add android`
`>> tns run android`

Upon giving location permission, an error is returned:
<details><summary> Error </summary> 

<pre><code>JS: ERROR Error: Uncaught (in promise): Error: Cannot enable the location service. com.google.android.gms.common.api.ApiException: 10: Not implemented on this platform.
JS: Error: Cannot enable the location service. com.google.android.gms.common.api.ApiException: 10: Not implemented on this platform.
JS:     at file:///data/data/org.nativescript.WearTest/files/app/tns_modules/nativescript-geolocation/geolocation.js:187:28 [angular]
JS:     at Object.onInvoke (file:///data/data/org.nativescript.WearTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:4798:33) [angular]
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.WearTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:4789:33) [angular]
</code></pre>
</details>

If we start watching location in this project (I put it after the enableLocationRequest() call) as below:

<pre><code>Location.watchLocation(function(location){
            console.log("Success");
            console.dir(location);
        },function(err){
            console.log("Failure" + err);
        },{minimumUpdateTime:2000});
</code></pre>

neither callback is ever called.

I'm wondering if this is an issue with the app, or something on my end. I am experiencing none of the above issues on a Samsung Galaxy Tab S2 running Android 7.0.

**Comment by zbranzov** [comment]
Hi @ThomasJFR,
As the error says I don't think that the platform you are using is supported and we don't have such Android wear device on our side to dig further.
