### ISSUE TITLE
NativeScript : An Uncaught Exception Occurred on main thread on android

### ISSUE THREAD

**Issue by FelixAVeras** [NativeScript/nativescript-geolocation#131]
### I'm working with NativeScript and Angular 

I am new to mobile development and I am working with NativeScript and in the Android application I find this error.

This is the error:

![screenshot-2018-05-25_13 31 33 606](https://user-images.githubusercontent.com/24570175/40558417-41aedeca-6021-11e8-8c72-deb6f4dab944.png)

**Comment by zbranzov** [comment]
Considering only the provided log I cannot say what might be the reason for your error and I'm not sure it is related to the geolocation plugin. Would you fill out the new issue form and provide all asked information. Additionally, if you provide a sample demo we might be able to investigate.

**Comment by olucus** [comment]
Remove folders node_modules, hooks and platforms and rebuild. Your versions of tns-core-modules and tns-core-modules-widget are not correct. https://github.com/NativeScript/NativeScript/issues/2772

**Comment by umutesen** [comment]
In my case, I was importing files using the `src/app/core/services` path instead of `../../../core/services`

**Comment by rostasan** [comment]
I had a similar obscure error and it turned out I had added
import "./livesync-navigation"; 
into my main.ts file which won't work with the " quote, I needed the single quote.
