### ISSUE TITLE
Error on iOS : The operation couldn't be completed. (kCLErrorDomain 0.)

### ISSUE THREAD

**Issue by NikolayBa** [NativeScript/nativescript-geolocation#132]
### Which platform(s) does your issue occur on?
- iPhone 6s
- iOS 11.3

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.0.1
- Plugin(s): 
"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-bluetooth": "^1.3.1",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-mapbox": "^4.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~4.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "4.0.1",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.5.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.10.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 

When iPhone's Location is lost for some reason.

I was testing the app today in the Sofia Subway, and when I managed to reproduce it twice - when entering inside and throughout half of the route.

![img_2366](https://user-images.githubusercontent.com/20954692/40628440-c0d1a972-62cd-11e8-987f-4ad5eca4339e.png)
![img_2367](https://user-images.githubusercontent.com/20954692/40628441-c2fb2ebc-62cd-11e8-8340-7bdef6b6b1ac.png)

The UI becomes unresponsive and I need to restart the app.

### Is there any code involved? 
```
 geoLocation.watchLocation(location => {
            this.currentGeoLocation = location;
            
        }, error => {
            alert(error);
        }, {
            desiredAccuracy: Accuracy.high,
            updateDistance: 10,
            minimumUpdateTime: 1000 * 1,
            updateTime : 5000
        });
```

I am updating the current location and passing lat and lng to a mapbox (using mapbox plugin) every second to re-center it's position.

**Comment by zbranzov** [comment]
There might be places where both gps and wifi services have no signal but we haven't been able to reproduce the same scenario as yours yet.
