### ISSUE TITLE
Does it support Nativescript 4.1.0?

### ISSUE THREAD

**Issue by zuohuadong** [NativeScript/nativescript-geolocation#136]
It is said that it is better for 3.4.6 support?

**Comment by zbranzov** [comment]
Yes, it supports the latest bits of NativeScript. The app in the repo is migrated so you could give it a try.

**Comment by zuohuadong** [comment]
I have some problems with the 4.0.2 process and it's not stable. I don't know, I should upgrade to 4.1.0 or demote to 3.4.1.
@zbranzov

**Comment by zbranzov** [comment]
@zuohuadong The plugin should be fully functional with the latest versions so the better option is to update it to 4.1.
