### ISSUE TITLE
Android 7.0/8.0 Request permission is not prompted

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-geolocation#144]
_From @liuchuancong on July 3, 2018 12:21_

   ``` <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

I don't have any tips on my phone （Android 8.0）

_Copied from original issue: NativeScript/NativeScript#6020_

**Comment by tsonevn** [comment]
_From @liuchuancong on July 3, 2018 12:34_

i want use geolocation,
on 6.0 i do it, but on 8.0 it can't

**Comment by tsonevn** [comment]
HI @liuchuancong,
I tested your case with our nativescript-geolocation demo app, however, was unable to recreate an issue with permission requests, while using Android 8. You can check the demo app [here](https://github.com/NativeScript/nativescript-geolocation/tree/master/demo). It will help if you provide more info about your environment(CLI, tns-core-modules, tns-android versions). Also, send us sample project, which can be used for debugging.

**Comment by liuchuancong** [comment]
@tsonevn thanks! I will try more

**Comment by zuohuadong** [comment]
@tsonevn  How I should solve it.

**Comment by tsonevn** [comment]
Hi @zuohuadong,
As I mentioned in my previous comment, I can not recreate a similar problem with the plugin's demo project. In the demo app, we are using `enableLocationRequest` [method](https://github.com/NativeScript/nativescript-geolocation#methods) to request for permissions. The method will also prompt the user to accept or denied the request. If you have a case that this does not work, send us a demo app, and we will research the issue.

**Comment by liuchuancong** [comment]
after 6.0 should  get location permissions dynamically
in nativescript how do it?

**Comment by NickIliev** [comment]
@liuchuancong you can use [nativescript-permissions](https://github.com/NathanaelA/nativescript-permissions) plugin to ask for permission runtime ([example](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/app.component.ts#L25-L38))

**Comment by zuohuadong** [comment]
@NickIliev No support nativescript 4.0+

**Comment by NickIliev** [comment]
@zuohuadong the plugin is working as expected with NativeScript 4+ (the linked example is using {N} 4+) - here is [another test application](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-geolocation/issue-144) demonstrating the above.

**Comment by zuohuadong** [comment]
@NickIliev 

The  nativescript-geolocation  use google service.

But it cannot be used in China.

**Comment by zuohuadong** [comment]
@NickIliev 
Can you help me? I have no other option.
Nativescript-geolocation Plug-ins need to be improved

What causes the need to rely on Google services?
 Can we make a new version without Google service?

**Comment by NickIliev** [comment]
@zuohuadong this seems like a request for an entirely new plugin as it would break all current users (if we totally change the API).

In would suggest that you investigate what map service is not blocked in mainland China and see if there is already created a plugin for NativeScript (or wrap the related library in your own plugin/project). (e.g. check [Mapbox](https://github.com/EddyVerbruggen/nativescript-mapbox))
