### ISSUE TITLE
In China, how to get positioning  (No Google service)  for Android 6.0+ 。

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-geolocation#145]
_From @zuohuadong on July 5, 2018 3:26_

I try to use https://github.com/NativeScript/nativescript-geolocation  but not work (Google service).

Also, I can not find any Plug - ins, such as Baidu Map, a map.

_Copied from original issue: NativeScript/NativeScript#6030_

**Comment by NickIliev** [comment]
Closing as duplicate and related to [https://github.com/NativeScript/nativescript-geolocation/issues/144#issuecomment-402992230](https://github.com/NativeScript/nativescript-geolocation/issues/144#issuecomment-402992230)
