### ISSUE TITLE
[Android] - Set the minimum displacement between location updates in meters

### ISSUE THREAD

**Issue by denisraison** [NativeScript/nativescript-geolocation#146]
Hello there,

I just have a question.
Why we can't set the setSmallestDisplacement when creating the LoationRequest for watching location in Android.

Did you guys had any issue doing that?

Thanks for the library it's awesome 💃 
Denis Raison

**Comment by etabakov** [comment]
Hey @denisraison, there is nothing preventing us to set the displacement. I guess we just haven't thought of it or haven't stumbled on suitable use case. 

If you feel like this is important, we will be more than happy to consider a pull requests that extends the `Options` type and adds displacements as an option.

Welcome to NativeScript!

**Comment by etabakov** [comment]
The "updateDistance" option is now respected on Android as well.
