### ISSUE TITLE
Support for "markingMode" flag

### ISSUE THREAD

**Issue by RinkalGohel** [NativeScript/nativescript-geolocation#149]
Hi there! 

Wanted to know whether your plugin will still be working fine if I add the flag of 'markingMode' set to 'none' in package.json file, as mentioned in one of the blogs of NativeScript release? 

Here is the link of the blog where the reference is made for the same: https://www.nativescript.org/blog/announcing-the-release-of-nativescript-3.2

Looking forward to an early reply. Thank you!

**Comment by etabakov** [comment]
After 5.1 all plugins owned by the NativeScript Team should be compatible with the markingMode: none option in their latest versions. If the app is using some of the nativescript-ui-* packages upgrading to the latest version of the packages might make the application more stable with markingMode: none.
