### ISSUE TITLE
WatchLocation firing randomly

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/nativescript-geolocation#150]
### Which platform(s) does your issue occur on?
Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 4.1.1
- Runtime(s): Android 4.1.3
- Plugin(s): Geolocation 4.2.6

### Please, tell us how to recreate the issue in as much detail as possible. 
When i run a WatchLocation with the following options, the callback never fires ever second. Sometimes its 5 or 10 seconds later.
```
options: {
        //desiredAccuracy: 3,
        //updateDistance: 0,
        //maximumAge: 1000,
        updateTime: 1000,
        minimumUpdateTime: 500,
        timeout: 1000
    },
```

**Comment by VladimirAmiorkov** [comment]
Hi @LorenDorez ,

I apologise for the late response. I tested the mentioned options in our demo application by changing [this](https://github.com/NativeScript/nativescript-geolocation/blob/master/demo/app/main-page.ts#L66-L80) code to: 

```
watchIds.push(geolocation.watchLocation(
    function (loc) {
        if (loc) {
            model.locations.push(loc);
        }
    },
    function (e) {
        console.log("Error: " + e.message);
    },
    {
        updateTime: 1000,
        minimumUpdateTime: 500,
        timeout: 1000
    }));
```

and the callback is correctly executed. If you can share with me more details and preferably a project that reproduces the issue it would be of great help in proceeding further with investigating this issue.

**Comment by devyaz** [comment]
I too get updates every 5 seconds yet watch is supposed to be continuous?  In my realtime location app it's proving very disappointing

**Comment by zbranzov** [comment]
@LorenDorez @devyaz According to Google's documentation https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#setInterval(long) the interval is inexact and may not occur at all so this delay is expected behavior.

**Comment by devyaz** [comment]
@Silko5 you are right google maps or nativescript-mapbox would never work
