### ISSUE TITLE
Geolocation distance not working well

### ISSUE THREAD

**Issue by JMente** [NativeScript/nativescript-geolocation#159]
### Make sure to check the demo app(s) for sample usage 
Yes, I do.
### Make sure to check the existing issues in this repository 
Yes, not found in actual issues
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Issue occurs after changes reloading application.

If i run the command `tns run android --clean` or `tns debug android --clean` don't crash but if i only run 
`tns run/debug android` without the directive --clean the distance method working fine the first compilation and fails after applications change refreshing.

### Which platform(s) does your issue occur on?
- Android Api 27 
- Device. What type of device? => Galaxy S6 Edge

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.2.3
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): Android 4.2.0
- Plugin(s):  nativescript-geolocation ^4.3.0 
### Please, tell us how to recreate the issue in as much detail as possible. 
First watch a locations every 3 seconds and push location in array, after call method distance sent the first element and the last element of these a code example
`
distance: (from, to) => {
    return Geolocation.distance(from, to);
  }
`

### Error log
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: 
System.err: TypeError: loc1.android.distanceTo is not a function
System.err: File: "file:///data/data/com.revive.countdown/files/app/tns_modules/nativescript-geolocation/geolocation.js, line: 271, column: 24
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'distance', file:'file:///data/data/com.revive.countdown/files/app/tns_modules/nativescript-geolocation/geolocation.js', line: 271, column: 25
System.err: 	Frame: function:'distance', file:'file:///data/data/com.revive.countdown/files/app/services/geolocation.js', line: 41, column: 24
System.err: 	Frame: function:'setInterval', file:'file:///data/data/com.revive.countdown/files/app/cycling/resume/resume.js', line: 31, column: 46
System.err: 	Frame: function:'invoke', file:'file:///data/data/com.revive.countdown/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 52, column: 48
System.err: 	Frame: function:'run', file:'file:///data/data/com.revive.countdown/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 56, column: 13
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
```
const startTracking = () => {
  // Geolocation is wrapped in a different module with default configurations.
  Geolocation.tracking((location) => {
    if (Is.not.undefined(location)) {
      locations.push(location);
    }
  });
  intervalId = setInterval(() => {
    counter += 1;
    ApplicationSettings.setNumber('counter', counter);
    viewModel.set('time', TimeModule.toTimeString(counter));
    if (locations.length > 1) {
      let loc = locations[locations.length - 1];
      viewModel.set('speed', loc.speed);
      // Here try to get a distance and crash
      viewModel.set('distance', (Geolocation.distance(locations[0], loc) / 1000).toFixed(2));
    }
  }, 1000);
};
```

**Comment by tsonevn** [comment]
Hi @JMente,
If you need to watch about the user location, you should use `watchLocation` method instead of `tracking `. Also, I tested the `distance` method with the latest `nativescript-geolocation` version `4.3.0`, however, was unable to reproduce the error or any problems with the method itself. For your convenience, I am attaching sample project, please review it and make the needed changes, which allow us to reproduce the issue.
[Archive.zip](https://github.com/NativeScript/nativescript-geolocation/files/2378338/Archive.zip)

**Comment by JMente** [comment]
Resolve the problem because serialized locations Array lost the android methods and data in all items, change the JSON serialize for navigationContext and works fine.
