### ISSUE TITLE
Error when accessing geolocation inside Web Worker

### ISSUE THREAD

**Issue by valera1401** [NativeScript/nativescript-geolocation#163]
Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
JS:     com.google.android.gms.common.zzo.isGooglePlayServicesAvailable(Unknown Source)
JS:     com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
JS:     com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
JS:     com.tns.Runtime.WorkerGlobalOnMessageCallback(Native Method)
JS:     com.tns.Runtime.access$400(Runtime.java:34)
JS:     com.tns.Runtime$WorkerThreadHandler.handleMessage(Runtime.java:267)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.os.HandlerThread.run(HandlerThread.java:61)

The error occurs when I try to get current location inside Web Worker.

context.onmessage = async (message) => {
    try {
        const lс = await geolocation.getCurrentLocation({
            desiredAccuracy: Accuracy.high,
            updateDistance: 0.1,
            updateTime: 3000,
            minimumUpdateTime: 100
        });
    }
    catch (e) {
        console.log(e);
    }

**Comment by DimitarTodorov** [comment]
Hi @valera1401 ,

Unfortunately I can't reproduce the issue you are facing, using the geolocation and web worker plugins. Could you please send us a demo project in which you observe the error.

Regards.

**Comment by JMente** [comment]
Hi i'm have the same issue this is my code in my worker.js
```
require("tns-core-modules/globals");
const Geolocation = require("nativescript-geolocation");
const Accuracy = require("tns-core-modules/ui/enums").Accuracy;

let options = { desiredAccuracy: Accuracy.high, maximumAge: 5000, timeout: 20000 };

global.onmessage = function(data) {
  Geolocation.getCurrentLocation(options).then(
    loc => {
      console.log(loc);
    },
    error => {
      console.dir(error);
    }
  );
};

```

**Comment by saike** [comment]
I had the same errors. I noticed that the geolocation service works correctly inside the components, but not inside the vuex store. Apparently, the application needs to fully boot before using the geolocation service. I wrapped the "created" hook inside main <Frame/> component in a timeout of 2 seconds and it worked as it should:

```
new Vue({

    template: `
        <Frame>
            <Home />
        </Frame>`,

    components: {
        Home
    },
    methods: {
        ...mapActions({
            startRecording:  'startRecording',
            enable: 'enable'
        })
    },
    created: function () {

        setTimeout(()=>{
            this.enable().then((enabled)=> {

                this.startRecording();
                console.log('app created', enabled);
                return enabled;
    
            }, (err) => {
                console.log(err);
            });
        }, 2000);

    },
    store: store
}).$start();
```

**Comment by eugv86** [comment]
> Hi i'm have the same issue this is my code in my worker.js
> 
> ```
> require("tns-core-modules/globals");
> const Geolocation = require("nativescript-geolocation");
> const Accuracy = require("tns-core-modules/ui/enums").Accuracy;
> 
> let options = { desiredAccuracy: Accuracy.high, maximumAge: 5000, timeout: 20000 };
> 
> global.onmessage = function(data) {
>   Geolocation.getCurrentLocation(options).then(
>     loc => {
>       console.log(loc);
>     },
>     error => {
>       console.dir(error);
>     }
>   );
> };
> ```

@JMente Did you ever figure this out?

**Comment by JMente** [comment]
> > Hi i'm have the same issue this is my code in my worker.js
> > 
> > ```
> > require("tns-core-modules/globals");
> > const Geolocation = require("nativescript-geolocation");
> > const Accuracy = require("tns-core-modules/ui/enums").Accuracy;
> > 
> > let options = { desiredAccuracy: Accuracy.high, maximumAge: 5000, timeout: 20000 };
> > 
> > global.onmessage = function(data) {
> >   Geolocation.getCurrentLocation(options).then(
> >     loc => {
> >       console.log(loc);
> >     },
> >     error => {
> >       console.dir(error);
> >     }
> >   );
> > };
> > ```
> 
> @JMente Did you ever figure this out?

Sorry, no buddy, the last time I'm see that project they move to use xamarin.
