### ISSUE TITLE
Location error on NS 5

### ISSUE THREAD

**Issue by kshipraShelke** [NativeScript/nativescript-geolocation#179]
After upgrade NativeScript to version 5, I have this error:

Cannot enable the location service. Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbck

There was also an issue (Closed Now) regarding this error but it is not solving the problem for me.

app.gradle looks like -

dependencies {
  compile 'com.google.gms:google-services:4.2.0'
}
android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.******"
    multiDexEnabled true
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
  } 
   project.ext {
    googlePlayServicesVersion = "15.0.1"
  }
}

**Comment by kshipraShelke** [comment]
Any suggestions on this issue?

**Comment by Mflm** [comment]
I have the same problem, also by downgrading android to 4.1.3.

Any solution?

**Comment by kshipraShelke** [comment]
Add this code in include.gradle file of the plugin.
It worked after re-build

android {
    project.ext {
        googlePlayServicesVersion = "15.0.1" 
    }
}

**Comment by Mflm** [comment]
Hi
It doesn't work

**Comment by Mflm** [comment]
The solution is with another file:

https://github.com/NativeScript/nativescript-geolocation/issues/172#issuecomment-438789843
