### ISSUE TITLE
Feature: Option to open Settings

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-geolocation#182]
Implement an option to present the user with the Permissions setting screen for the current application if `isEnabled` returns false.

**Comment by DimitarTodorov** [comment]
Hi @bradmartin 

The feature is implemented in the latest version of nativescript-geolocation @4.4.0, which is now published to npm.

**Comment by Ahnert1** [comment]
When using version 4.4.0, my nativescript-angular app shows this error when executing "tns build ios":

`ERROR in node_modules/nativescript-geolocation/location-monitor.d.ts(112,48): error TS2304: Cannot find name 'CLAuthorizationStatus'.`

I reverted to 4.3.1 to avoid this issue.

**Comment by DimitarTodorov** [comment]
Hi @Ahnert1 ,

Can you please provide us a sample app where the issue can be reproduced and steps to reproduce it.

**Comment by Ahnert1** [comment]
@DimitarTodorov 

I have a sample nativescript playground app which has nativescript-geolocation@4.4.0 installed.
https://play.nativescript.org/?template=play-ng&id=V3eMs1

To view the error, simply open the file `location-monitor.d.ts` located here:

![image](https://user-images.githubusercontent.com/43629293/51760960-64807e00-2091-11e9-8f45-967730db55ca.png)

You will now see that an Error has appeared:

![image](https://user-images.githubusercontent.com/43629293/51761025-9b569400-2091-11e9-9c73-5da0243dd6c7.png)

I have created another playground app which has nativescript-geolocation@4.3.1 (previous version) installed.
https://play.nativescript.org/?template=play-ng&id=IquSwo

No error will be displayed when following the same steps as above.
