### ISSUE TITLE
when I set enableLocationRequest(true) there are tree options in the popup but only one resolves

### ISSUE THREAD

**Issue by janossuta** [NativeScript/nativescript-geolocation#184]
Hi,

When I set enableLocationRequest(true) on iOS there are tree options in the popup but only one resolves the other two get rejected.

![webp net-resizeimage 7](https://user-images.githubusercontent.com/16418295/51143864-e7af0200-184f-11e9-8f77-0689161157b6.png)

When I tap on the **Always Allow** it resolves and I can set the location immediately 
but if I choose **Only while using the App** it get rejected but the location is available if I tap again on the get location button.
Finally, if I choose **Don't allow** it get rejected also.

this is how I use it

```javascript

getLocation() {      
        
        isEnabled().then(isLocationEnabled => {                 
            if (isLocationEnabled) {
                this.useLocationService();
            } else {
                enableLocationRequest(true).then(() => {                    
                    this.useLocationService();
                },(err)=>{
                    console.log(err);
                });               
            }            
        }, function (e) {
            console.log("Location error received: " + (e.message || e));
        });  
    }
	
	
useLocationService(){
       
        getCurrentLocation({
            desiredAccuracy: Accuracy.high,
            timeout: 5000
        })
            .then(location => {

                console.log(location.longitude, location.latitude); 
            }).catch(error => {
                 console.log('Location ERROR: ');
                 console.log(error);
                 console.log(localize('cant_update_the_location'));      
            });
    }


```

**So my question is, how can I tell the difference between the two rejection?**

### Which platform(s) does your issue occur on?
- iOS
- emulator and device

### Please, provide the following version numbers that your issue occurs with:
 version: "4.3.1",

**Comment by tbozhikov** [comment]
Thanks for reporting this, @janossuta! Indeed, I was able to reproduce this behavior when calling enableLocationRequest() with `always` parameter set to **true** and when chose **Only while using the App**. Will be fixed.

**Comment by DimitarTodorov** [comment]
Fix is available in the latest release of nativescript-geolocation@4.4.2
