### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbck

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/nativescript-geolocation#187]
### Make sure to check the existing issues in this repository 
Relates to issues #156 & #173.

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Running this plugin in my app on Android, I get an error:

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbck

If I add [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#google-play-services-version) to the `demo-angular` project of this plugin, it will also result in the same error when trying to use the geolocation plugin.

The issues mentioned above suggest to either pin Google Play Services to version 15.0.1 or use latest (+) as below, with the latter also recommended in the [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#google-play-services-version) docs:

```
project.ext {
    googlePlayServicesVersion = "15.0.1"
}
```
OR
```
project.ext {
    googlePlayServicesVersion = "+"
}
```

This will still result in the same `NoClassDefFoundError`.

### Which platform(s) does your issue occur on?
Android both with emulator and real device

### Please, provide the following version numbers that your issue occurs with:

```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.1 version and is up to date.
✔ Component tns-core-modules has 5.1.2 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.1 version and is up to date.
```

Relevant plugins:
```
"nativescript-geolocation": "^4.3.1",
"nativescript-plugin-firebase": "^7.5.0",
```

**Comment by tbozhikov** [comment]
Hi @abhayastudios, @MaxiSonntag. Here's how I managed to use both plugins (geolocation and firebase) together:
1. Use demo-angular project from the geolocation repo, add nativescript-plugin-firebase plugin v7.7.0
2. Create a file **before-plugins.gradle** in **/demo-angular/App_Resources/Android**
3. Add content:
```
project.ext {
    googlePlayServicesVersion = "+"
}
```

This procedure is also described [here](https://github.com/NativeScript/nativescript-geolocation/blob/b910f8c290ceee1beed3a23f9959892424f21eb7/demo-angular/App_Resources/Android/app.gradle#L10).
Hope this helps!

**Comment by JMente** [comment]
@tbozhikov this orks for me, thank you

**Comment by abhayastudios** [comment]
@tbozhikov sorry for the delay but indeed this solves my issue! thanks a lot :)
