### ISSUE TITLE
iOS enableLocationRequest popup closes too fast

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-geolocation#19]
I have the following code in the loaded event of a view
```ts
if (!geolocation.isEnabled()) {
    geolocation.enableLocationRequest();
}
```

The popup shows very briefly on the screen and disappears after around 1.5 seconds (on simulator). According to http://stackoverflow.com/a/9474095/5272836 this is usually because `CLLocationManager` gets disposed by GC before the user can respond.

**Comment by ignaciolarranaga** [comment]
+1
