### ISSUE TITLE
Error: Location service is disabled

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/nativescript-geolocation#2]
The plugins throws the "Location service is disabled" when the location is already enabled

**Comment by aderbas** [comment]
I do not know if it's the same problem but: https://github.com/NativeScript/NativeScript/issues/1434

**Comment by sivaramsi** [comment]
JS: Unhandled Promise rejection: Location service is not enabled or using it is not granted. ; Zone: <root> ; Task:  ; Value: Error: Location service is not enabled or using it is not granted.
JS: Error: Uncaught (in promise): Error: Location service is not enabled or using it is not granted.

I got this
