### ISSUE TITLE
enableLocationRequest() should have a callback

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-geolocation#21]
I think it should be a callback or some way to get notified about the user response.

Right now the only option is polling to know if the enable location changes I guess ?

**Comment by hshristov** [comment]
enableLocationRequest() now returns a Promise<void> - in master branch. Please test it and if everything works as expected I will publish it on npm.

**Comment by burkeholland** [comment]
This is a wonderful enhancement! Can we go ahead and have this pushed up to npm? Thank you so much for implementing this.

**Comment by hshristov** [comment]
@burkeholland It should be live :)

**Comment by burkeholland** [comment]
Thank you so very much!

**Comment by anodal88** [comment]
Hi i am relatively new with nativescript and i am using this plugin, can you put an example where explain how to catch the user response after use "enableLocationRequest()", thanks

**Comment by IRCraziestTaxi** [comment]
@hshristov I have the same question as @anodal88 - why does the promise not return a boolean indicating the user's response?

**Comment by IRCraziestTaxi** [comment]
@hshristov Sorry, disregard previous comment.

@anodal88 In case you never discovered the answer (and for the benefit of anybody else like me who was trying to figure it out) - it is a promise of void that resolves if the user accepts or throws an error (which you may `catch`) if the user declines.

I think a boolean would have been more graceful and easier to work with, but it works.
