### ISSUE TITLE
Get current location for many users at the same time

### ISSUE THREAD

**Issue by charlie884** [NativeScript/nativescript-geolocation#220]
Hi,

How can i get current location at the same time around X kilometer for many users in the map and set markers for each user.

**Comment by tgpetrov** [comment]
Hi @charlie884 
This plugin can be used to determine the location of the device that is currently running the application that uses the plugin. When you have that information for every user of your app, you can store it online, retrieve it in the app to show it on a map, but this is all far beyond this plugin's scope.
