### ISSUE TITLE
watchLocation does not work on my end

### ISSUE THREAD

**Issue by ickata** [NativeScript/nativescript-geolocation#23]
Hi,

 ```watchLocation``` appears not to be working on my end on iOS, both in the simulator and test device (iPhone).

Code:

```
    geolocation.watchLocation(
      updatePosition,
      function ( e ) {
         alert( 'Error updating position: ' + e.message )
      },
      {
         desiredAccuracy : 10,
         updateTime : 2500
      }
    );

function updatePosition( loc ) {
   console.log( 'Location updated', loc );
}
```

The ```updatePosition``` is never called. 

From time to time I get the error callback called, but not always. 

Let me know what further details to provide.

**Comment by ickata** [comment]
This might be related: ```getCurrentLocation``` always returns the same location, no matter if I change it.

```
function getLocation( callback ) {
    var location = geolocation.getCurrentLocation({
         desiredAccuracy : 10,
         // maximumAge : 15000,
         timeout : 15000
      }).
    then(function(loc) {
        if (loc) {
            callback( loc );
        }
    }, function(e){
         console.log('Error getting location', e.message);
        alert("Error getting location: " + e.message);
    });
}
```

It works on Maps though. Check:
https://youtu.be/B5NTljptcx4

You can also see how often I get the timeout error (this ```getLocation``` function is being called in an interval as ```watchLocation``` does not work).

**Comment by ickata** [comment]
In addition: I'm having the same problem with the deprecated ```location```.

**Comment by hshristov** [comment]
@ickata I've merged few fixes in the master branch that should fix this problem. Could you try with the master branch at write back if the problem is fixed?

**Comment by ickata** [comment]
@hshristov ,

Let me know how to test with master branch, as running

```npm install https://github.com/NativeScript/nativescript-geolocation/tarball/master/source```

does not work - returns error

**Comment by ickata** [comment]
@hshristov ,

I tested with master version (manually created a tarball from the ```./source/```directory and added the plugin with ```tns plugin add ./geolocation-master.tar.gz```) and it appears that the timeout error is no more (I need to try few more times to confirm). However - the current location is still not updated when I change it from the Simulator settings. 

Let me know what additional info to provide.

**Comment by hshristov** [comment]
@ickata I've tested changing location in Simulator and I get newer coordinates when I change the location from Debug -> Location. Could you attach project which reproduce the issue?

**Comment by ickata** [comment]
I'm currently playing with the [sampleGroceries](https://github.com/NativeScript/sample-Groceries) demo app, just added the [Google Maps plugin](https://github.com/dapriett/nativescript-google-maps-sdk) and the location (this) plugin to the main view.

**Comment by ickata** [comment]
@hshristov ,

Here are the steps to reproduce (I tried them to make sure I will reproduce the issue again):

1. Checkout sampleGroceries demo app ```git clone git@github.com:NativeScript/sample-Groceries.git```

2. Switch to "start" branch ```git checkout start```

3. Copy the [modified files](http://ickata.net/sampleGrocceries-start-modified.zip) in the directory and unzip ```unzip -o sampleGrocceries-start-modified.zip```

4. Add iOS + plugins:

```
tns platform add ios
tns plugin add nativescript-google-maps-sdk
tns plugin add nativescript-geolocation geolocation.tar.gz
```

5. Run in the Simulator ```tns run ios --emulator```

**Comment by hshristov** [comment]
@ickata I'm using the test app:
https://github.com/nsndeck/locationtest

I have modified the XML a little bit so that ListView height is set to hardcoded value otherwise you will see a single row even if there are multiple.

Then in the simulator Debug->Location I change the location and use the Get Current Location button. Keep in mind that the options you specify affects the location that is returned.

**Comment by ickata** [comment]
@hshristov ,

I did the following:

1. Removed all tns plugins
2. Removed iOS platform support
3. Added iOS platform support
4. Added the plugins

This somehow solved the problem. However, this is the second time I solve a tns issue with remove & add ios platform support. Maybe several remove & add of plugins makes a mess and ios remove cleans up that mess...

**Comment by ickata** [comment]
Well, actually this appears to work:

```
geolocation.watchLocation(
      updatePosition,
      function ( e ) {
         alert( 'Error updating position: ' + e.message )
      },
      {desiredAccuracy: 3, updateDistance: 10, updateTime: 1000 * 20}
    );
```

And this not:

```
    geolocation.watchLocation(
      updatePosition,
      function ( e ) {
         alert( 'Error updating position: ' + e.message )
      },
      {
         desiredAccuracy : 10,
         updateTime : 2500
      }
    );
```

It appears that I updated the options before writing the above post and actually this solves the problem.

**Comment by hshristov** [comment]
The default `updateDistance` is 0 meters and default `minTimeUpdate` is 1 minute.
And in that demo the `options` object incorrectly specify `updateTime` when it should be `minimumUpdateTime`
