### ISSUE TITLE
how to create a foreground service for real-time tracking

### ISSUE THREAD

**Issue by LKTPD** [NativeScript/nativescript-geolocation#231]
It seems a background service for tracing in real time shall not be working if SDK version >26(Android8.0), here comes up a article and codes of Android Studio on creating a foreground service claim that it work, I'm not faimilar with native android codes, and no idea on how to create a foreground service in NativeScript, could somebody help to release a demo? @elena-p 

Ref1: [https://hackernoon.com/android-location-tracking-with-a-service-80940218f561](https://hackernoon.com/android-location-tracking-with-a-service-80940218f561)
Ref2: [https://bitbucket.org/tiitha/backgroundserviceexample/branches/](https://bitbucket.org/tiitha/backgroundserviceexample/branches/)

**Comment by LKTPD** [comment]
Thanks to @jnorkus's issue, a foreground service example in NativeScript could be found here and downloaded for reference.
[https://github.com/NativeScript/NativeScript/issues/6994](https://github.com/NativeScript/NativeScript/issues/6994)
[https://github.com/NativeScript/NativeScript/files/2940493/ns-test-android.zip](https://github.com/NativeScript/NativeScript/files/2940493/ns-test-android.zip)

**Comment by pianetarosso** [comment]
Hi, currently I'm getting a 
```
 ERROR Error: java.lang.Exception: Failed resolving method startForegroundService on class android.content.ContextWrapper
```

When trying to run it on a emulator. Do you know how to solve it?
