### ISSUE TITLE
JS: Error: Location not enabled.

### ISSUE THREAD

**Issue by jasenkabalac** [NativeScript/nativescript-geolocation#239]
In demo-angular enable location does not work for me

**Comment by tbozhikov** [comment]
Hi @jasenkabalac. Please, tell us how to recreate the issue in as much detail as possible. Can you share any details on what device you get it, what versions of the plugin and NativeScript CLI you experience this? Have you done any modifications to the code? Did you try deleting the node_modules, platforms and hooks folders inside demo-angular and then retrying?

**Comment by tbozhikov** [comment]
In addition to my previous post, please check if you have previously denied the location for the app.
