### ISSUE TITLE
NS 6+ compatibility: .enableLocationRequest() doesn't work

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/nativescript-geolocation#246]
### Which platform(s) does your issue occur on?
- Android
- Android versions: 9
- Mi device running Android 9 custom rom

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.0.1
- Runtime(s):  `"tns-android": 6.0.0` 
- Plugin(s): `"nativescript-geolocation": "5.1.0",`

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

lib does not request for geolocation permissions in NS 6+ on using `.enableLocationRequest()` method. 
A simple log saying `No v4 support` is added to console each time instead
The lib internally uses `"nativescript-permissions": "~1.3.0"` which is outdated(I think so!?). 
The [library](https://github.com/NathanaelA/nativescript-permissions/blob/master/src/README.md) is currently at version 1.3.7 and is compatible with androidx according to the latest commits there. 

### Temporary solution
Installed the latest `nativescript-permissions` library manually

**Comment by Prefix1802** [comment]
For IOS 13 this also does not work i.c.w. NS 6.

Need help ASAP :)

**Comment by xsterlas** [comment]
I have the same problem on android 7 and NS 6.1.2.
The exception on mobile:
"An uncaught Exception occurred on GoogleApiHandler thread. Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations".
I added the permissions to de manifest but the error continues.
Hope to help someone to find a solution...

**Comment by aaayushsingh** [comment]
@xsterlas @Prefix1802 add the latest nativescript-permissions lib to your project and import it anywhere. This will fix the issue

**Comment by Prefix1802** [comment]
I solved it by adding:

nslocationalwaysandwheninuseusagedescription <- This one for IOS 13
nslocationwheninuseusagedescription <- This one for IOS 12.4
nslocationalwaysusagedescription

To myproject-info.plist in platforms/ios/myproject and make sure to include it in node_modules/nativescript-geolocation/platforms/ios/info.plist.

**Comment by xsterlas** [comment]
@aaayushsingh thank you very much! It solved the problem with all the plugins needs to use permissions.

**Comment by elena-p** [comment]
@aaayushsingh, thank you for your answer.

There is an [issue](https://github.com/NativeScript/nativescript-dev-webpack/issues/1037) logged in nativescript-dev-webpack that is currently in progress.
