### ISSUE TITLE
Location tracking in background, location watcher is not detecting location changes.

### ISSUE THREAD

**Issue by karo-dc** [NativeScript/nativescript-geolocation#251]
is there a detailed documentation for location's tracking in background?
there are several closed issues about it but it's not clear if the solutions are within the plugin or should i write a separate code?
### Which platform(s) does your issue occur on?
- Both 
- iOS >10 
- Android >7 
- device

**Comment by tbozhikov** [comment]
Hey @karo-dc, the entire documentation of the plugin is in the [README](https://github.com/NativeScript/nativescript-geolocation/blob/master/README.md) file.

Regarding tracking in background on Android, refer [this file](https://github.com/NativeScript/nativescript-geolocation/blob/master/demo/app/background-service.ts).
For iOS, there is an option `iosAllowsBackgroundLocationUpdates`, documented [here](https://github.com/NativeScript/nativescript-geolocation#options).
This [issue comment ](https://github.com/NativeScript/nativescript-geolocation/issues/233#issuecomment-521994308) could give you other hints as well. 

Hope this helps!
