### ISSUE TITLE
Application crashes when using the plugin to get location geoLocation.isEnabled()

### ISSUE THREAD

**Issue by ajdadj1987** [NativeScript/nativescript-geolocation#269]
Which platform(s) does your issue occur on?
- Android
- CLI: 6.7.8
- Cross-platform modules: 3.0.0

I'm trying to use this plugin for my app. I need the lat and long of my current position. Demo code works perfect for angular.

When i run my angular app using geo-location, i'm calling below as per demo.

geoLocation.isEnabled().then(function (isEnabled) {

I do get a pop up but when i click allow when using the app, it crashes without error and upon debugging i found it crashes in below code of the plug-in.

let mLocationRequest = new com.google.android.gms.location.LocationRequest();
         
Please advise. Thank you

**Comment by codeturn** [comment]
Same bug then "nativescript-google-maps-sdk" in dependencies. Looks as conflict with google maps sdk.

**Comment by geek3000** [comment]
Same bug

**Comment by ajdadj1987** [comment]
Looks like mine was resolved upon resolving Google Play Services version.
In order to fix this you might pin the version number in your app/App_Resources/Android/before-plugins.gradle file (if the file does not exist, just create it):

android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "16.+"
  }
}

I hope it does for you as well.

Good Luck @codeturn @geek3000 !!
