### ISSUE TITLE
Timeout while searching for location - Angular 2

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-geolocation#30]
## Description Of The Issue

When requesting a users location after a successful location services request, the `getCurrentLocation` method times out.

````typescript
import {Component, OnInit} from "@angular/core";
var geolocation = require("nativescript-geolocation");

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent implements OnInit {
    status:string = "Location services not enabled";
    
    ngOnInit() {
        if (!geolocation.isEnabled()) {
           geolocation.enableLocationRequest().then(() => {
                this.getLocation();
            });
        }
        else {
            this.getLocation();
        }
    }

    getLocation() {
       // this method times out when called from the enableLocationRequest promise
        geolocation.getCurrentLocation({ timeout: 20000 }).then((location) => {
            this.status = `Latitide: ${location.latitude}, Latitude: ${location.longitude}`;
        });
    }
}
````

### Expected Result

The application should request access to the user's location and then display their latitude and longitude.

### Actual Results

The `getCurrentLocation` method times out.

[geolocation-timeout-log.txt](https://github.com/NativeScript/nativescript-geolocation/files/425178/geolocation-timeout-log.txt)

## Steps To Recreate

1. `tns create geolocation --ng`
2. replace the code in app.component.ts with the code above
3. `tns livesync ios --emualtor --watch` or `tns livesync android --watch` (Android Studio Emulator)

## Environment Configuration

* NativeScript CLI 2.2.1
* Node 5.4.0
* iOS Simulator version 9.3
* Android API version 22 Emulator

**Comment by burkeholland** [comment]
Note that this same behavior is also present in vanilla NativeScript (no Angular). This happens in both the `navigatedTo` and `loaded` events.

**Comment by vchimev** [comment]
Hi @burkeholland,

Could you please go to the iOS Simulator menu > Debug > Location > choose some of the options and start your app again?

I gave a try to your case and observed the described behavior when I did not set a location to the iOS Simulator. Then the app started, waited for the given timeout of 20 sec and crashed as the iOS Simulator didn't have a location to provide. After the steps above, the app worked as expected.

**Comment by burkeholland** [comment]
Thank you! It looks like it was because I had a custom location set. There is something wrong with the iOS emulator in that it doesn't recognize a custom location on emulator launch. You have to change it to some predefined location (say Apple), then you can put it back to custom.

Still researching the Android side, but I think we can safely close this as "Emulator/Simulator Issue" that needs to be documented when we write the section for ng-book.

**Comment by vchimev** [comment]
Hey @burkeholland,

For the Android side you could check out:
1. The emulator should use the *Google APIs System Image*; [here] (http://screencast.com/t/HIlQyJQL) is a reference to the Android SDK Manager.
2. In the Settings menu, the Location option should be turned ON.

**Comment by toddanglin** [comment]
I ran in to this same challenge with the iOS Simulator and geolocation timeouts.

Burke's solution worked for me, too, even though I had not set a custom location. I was using the standard/default "Apple" location. Simply changing this location to "None" and then back to "Apple" in the `Debug > Location` menu fixed the simulator. Now `getCurrentPosition` does not timeout.

It appears there is indeed an odd behavior in the iOS Simulator that requires you to change the Location value at least once to set it.
