### ISSUE TITLE
“JS: permission not granted!!!” although never asked

### ISSUE THREAD

**Issue by einicher** [NativeScript/nativescript-geolocation#31]
Hi,

on Android 6 `geolocation.enableLocationRequest()` sometimes does not work.
I get a message “JS: permission not granted!!!” in the console, although the prompt for it never came up, but nothing else happens, the error function inside `.then()` does also not get called (success function neither).

Deleting the app does not change anything, after some hours it then suddenly works again.

edit: had wrong function its about enableLocationRequest not getCurrentLocation

**Comment by iagui** [comment]
Experiencing the same issue in Android 7.

**Comment by nsndeck** [comment]
Closing it, because we recently update the plugin to support Android 6+. 
If the problem persist just re-open the issue.

**Comment by Skintillion** [comment]
For me it only added the FINE_LOCATION and it didn't ask for permissions it just gives the permission not granted error as above.

>JS: requestCode: 5000 permissions: [Ljava.lang.String;@15f691c grantResults: [I@f4e7925 
>JS: permission not granted!!!
