### ISSUE TITLE
enableLocationRequest promise elusive? 

### ISSUE THREAD

**Issue by TimAtExc** [NativeScript/nativescript-geolocation#37]
i am having this problem on ios 10:  can't seem to get my hands on the promise returned by enableLocationRequest.  Here's a snippet:

geolocation.enableLocationRequest()
.then(() => {
      resolve();
 })
 .catch((err) => {
   reject(err);
 });

neither 'then' nor 'catch' branches execute.  the next thing i see is the code which calls the above reporting an exception: 'Authorization denied'.  what am i doing wrong here?

thanks!

**Comment by nsndeck** [comment]
I've checked this case and everything works great but the syntax should be a little bit different:

```
geolocation.enableLocationRequest()
.then(() => {
resolve();
}, (err) => {
reject(err);
});
```

If you still encounter the issue please re-open the issue.

**Comment by dimitriospafos** [comment]
Allow location access from preferences for your app
