### ISSUE TITLE
"getCurrentLocation" response is very slow, unless using together with google maps sdk

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/nativescript-geolocation#38]
When I start the app for the first time, everything works fine:
1. I get my location in 1-3s

```
geolocation.getCurrentLocation({
	desiredAccuracy: 3, 
	updateDistance: 1, 
	maximumAge: 20000, 
	timeout: 20000
}).then(function(loc) {
	console.log(JSON.stringify(loc, null, 4));
	if (loc) {
		return loc;
	}
}).catch(function(response){
	console.log(response);
});
```

2. In about 5-10s I am asking for my location again. It also returns it in 1-3s.

3. Then I start `nativescript-google-maps-sdk plugin`. Also I enable `setMyLocationEnabled`, that enables locate_me button and blue_pin as my device on the map:

```
gMap.setMyLocationEnabled(true);
```

4. At this point I am updating my current location every 10s and it returns it in 1-3s. All is well.

*PROBLEM*

If the app has been opened at least once before, and it has cached its data now, opening it the second time makes my `getCurrentLocation` get response very slowly. 

1. I ask my location (repeatedly, until I get it), but it will return `Error: Timeout while searching for location!` at first try, then it will return it correctly at second try.

2. In about 5-10s I am asking for my location again. However, it will behave exactly like in point 1. 

3. I start the gmaps plugin, enabling `setMyLocationEnabled`.

4. Now every continuous `getCurrentLocation` returns the location normaly in 1-3s.

*Conclusion* - there is some sort of problem in getting the location data, probably bad interaction with caching data. And this problem dissappears when `nativescript-google-maps-sdk plugin` plugins `setMyLocationEnabled` method is enabled.

Tested on Android.

**Comment by nsndeck** [comment]
Hi @dxshindeo,

I've just published a new version on npm (0.0.16). Could you please try it and let me know if you still experience the problem with `getCurrentLocation`?
Thank you in advance.

nsndeck

**Comment by dxshindeo** [comment]
Unfortunately the issue still persists. Did you manage to reproduce the issue? If not, I could make a blank project to show it, when I have more free time. For now, workaround for this issue is calling Googles `LocationServices.FusedLocationApi` manually.

**Comment by dxshindeo** [comment]
Oh my, now the problem is more severe - updated my packages to versions listed below, and now every request fails and returns timeout forever, even after gmaps plugin initialization.

package.json:
```
{
  "//": "@angular higher than 2.1.2 causes listview to break its height and childs, in search view",
  "description": "Application",
  "license": "",
  "readme": "",
  "repository": "",
  "nativescript": {
    "id": "org.nativescript.Test",
    "tns-android": {
      "version": "2.3.0"
    },
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.3.0",
    "@angular/compiler": "2.3.0",
    "@angular/core": "2.3.0",
    "@angular/forms": "2.3.0",
    "@angular/http": "2.3.0",
    "@angular/platform-browser": "2.3.0",
    "@angular/platform-browser-dynamic": "2.3.0",
    "@angular/router": "3.3.0",
    "nativescript-angular": "1.2.0",
    "nativescript-geolocation": "0.0.17",
    "nativescript-gif": "^1.0.8",
    "nativescript-google-maps-sdk": "^1.4.1",
    "nativescript-phone": "^1.2.3",
    "nativescript-platform-css": "^1.0.1",
    "nativescript-vibrate": "^1.1.2",
    "reflect-metadata": "^0.1.8",
    "tns-core-modules": "2.4.2",
    "tns-platform-declarations": "^2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.20.0",
    "babel-types": "6.20.0",
    "babylon": "6.14",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.3",
    "typescript": "^2.0.10",
    "zone.js": "^0.7.2"
  }
}
```

**Comment by dxshindeo** [comment]
Ah, there we go - when compiling, I am getting this warning:
`nativescript-geolocation 2.4.0 for android is not compatible with the currently installed framework version 2.3.0.`

**Comment by dxshindeo** [comment]
To fix the upper mentioned warning, download nativescript CLI anew, to update it.
So, conclusion - your 0.0.17 version has fixed that caching/timeout bug, thank you!
