### ISSUE TITLE
Http service not getting called

### ISSUE THREAD

**Issue by MadhuSudhanBhaskar** [NativeScript/nativescript-geolocation#40]
Hi,

I have a service in "enableLocationRequest" callback, I see the service function being called but I dont see the service making a http request. This is happening when I make a fresh install of app on emulator. 

But if I force kill the app and open it again, I see it to getting all the data. This is happening in Android, have not tested it on IOS.

I have latest build of TNS.

I have some basic code uploaded here
https://github.com/MadhuSudhanBhaskar/NativeNew
Upfront Not a production code

**Comment by nsndeck** [comment]
I've tested your scenario and everything seems OK at least for `nativescript-geolocation` part. However `@angular/http` module need some more configuration in order to work. I've just added a call to `subscribe` method which triggers the http request.

```
 UserService.prototype.getCityDetails = function () {
        console.log('service call');
        var listCities$;
        this.http
            .get("" + this.baseUrl, { headers: this.getHeaders() })
            .map(mapPersons)
            .catch(handleError)
            .subscribe(function (r) {
            console.log("subscribe called with " + r);
            listCities$ = r;
        });
        console.dump(listCities$);
        return listCities$;
    };
```

Let me know how this works on your end.

**Comment by MadhuSudhanBhaskar** [comment]
Hi @nsndeck 
Will try it and keep you posted!

Regards,
Madhu

**Comment by MadhuSudhanBhaskar** [comment]
@nsndeck I see data coming, but I can't return it back to the called function. I am using Typescript.

**Comment by MadhuSudhanBhaskar** [comment]
```
    getCityDetails()  {
        console.log('service call');
        return Observable.create(observer => {
            var listCities$;
               this.http
                 .get(`${this.baseUrl}`, {headers: this.getHeaders()})
                 .map(mapPersons)
                 .catch(handleError)
                 .subscribe((r) => {
                    listCities$ = r;
                    observer.next(listCities$);
                    observer.complete();
                  });
        });
    }
```
This is for service
```
                this.userservice.getCityDetails().subscribe((r) => {

                    console.log('after service call');
                    this.myItems = r;
                    console.dump(this.myItems[0]);
                });
```
I can dump data, but not able to assign data to list view. Can you please help me here :)

**Comment by nsndeck** [comment]
Hi @MadhuSudhanBhaskar,

ListView cannot work with RxObservable's directly. You should use `async` pipe. [Here](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/list/list-test-async.ts#L17-L23) is an example of using async pipe with nativescript-angular.
