### ISSUE TITLE
Component variables not updated while watching location.

### ISSUE THREAD

**Issue by echap** [NativeScript/nativescript-geolocation#43]
Hello, new issue, but might not be related to nativescript geolocation but maybe angular data-binding.

```

public wid:number;
public distance:number = 0;
public lastLocation:any;

watchLocation() {
        if(!this.wid) {
            this.wid = geolocation.watchLocation((location) => {
                    this.updateDistance(location);
                },
                function(e){
                    console.log("Error: " + e.message);
                },
                { desiredAccuracy: Accuracy.high, updateDistance: 1, minimumUpdateTime: 1000 })

        }
    }
}

updateDistance(location) {
   this.distance = this.distance + geolocation.distance(this.lastLocation, location);
   this.lastLocation = location;
  console.log(distance);
}
```

This is a sample code of a TS file that watches location. On the other hand, I have my view with :

```
<Label [texŧ]="distance"></Label>
```

ISSUE is there : distance label is not updated **until I cut the watcher**. Anything about it ? :+1:

**Comment by echap** [comment]
My quick fix (that doesn't sound very nice to me...) :
```
<Label [text]="distance" id=distanceLabel>
```

update function : 
```
updateDistance(location) {
   this.distance = this.distance + geolocation.distance(this.lastLocation, location);
   this.lastLocation = location;

this._page.getViewById("distanceLabel").android.setText(this.getDistanceFormatted());
  console.log(distance);
}
```

**Comment by nsndeck** [comment]
Hi @echap,

The problem is that code is executed outside angular 2 zone. You can call `this.zone.run(() => {this.updateDistance(location);});`, of course you should have to inject NgZone:

```
import { NgZone } from "@angular/core";
...
constructor (private zone: NgZone...)
```

**Comment by echap** [comment]
Thanks @nsndeck, sounds like a very good explaination to me. Still, if there is not too many drawbacks including it in the angular zone would be much more understandable. Or at least, mention it in the docs 😉

**Comment by nsndeck** [comment]
@echap This is just a workaround later today I'll publish a new version which should be OK with your first code. Actually `nativescript-geolocation` plugin will do the dirty zone job :-).
