### ISSUE TITLE
Geolocation not work for me.

### ISSUE THREAD

**Issue by aderbas** [NativeScript/nativescript-geolocation#5]
I'm created a simple project using a sample for geolocation. Follow the tutorial (https://docs.nativescript.org/hardware/location) but I am getting the following error: http://pastebin.com/WyqSaBUi

Added permission in AndroidManiest.xml
```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```
Do you need anything else?

**Comment by aderbas** [comment]
```
com.tns.NativeScriptException: Calling js method onMapReady failed Error: java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION
```
But in AndroidManiest.xml have that permission

**Comment by aderbas** [comment]
I'm read logcat from device and found this:

```
E art     : invalid stream - problem with parameter iterator in /data/user/0/org.nativescript.MyApp/code_cache/secondary-dexes/com.google.android.gms.maps.OnMapReadyCallback_ftns_modules_nativescript-googlemaps_nativescript-googlemaps_l26_c25__-1453834539961-1.jar for method void com.tns.gen.com.google.android.gms.maps.OnMapReadyCallback_ftns_modules_nativescript-googlemaps_nativescript-googlemaps_l26_c25__.onMapReady(com.google.android.gms.maps.GoogleMap)
```
I'ts causes when I open the app (MyApp).

**Comment by aderbas** [comment]
I found the problem but I can not fix. Android Marshmallow the app need to ask the user for permission to access the user's geolocation. I do not know how to solve this using NativeScript.

**Comment by hdeshev** [comment]
Closing this one in favor of NativeScript/NativeScript#1434
