### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new nativescript_geolocation_1.Location()')

### ISSUE THREAD

**Issue by efdeveloper** [NativeScript/nativescript-geolocation#50]
My package.json is as follows:
"nativescript": {
    "id": "org.nativescript.test",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-couchbase": "^1.0.17",
    "nativescript-geolocation": "0.0.19",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }

I get the following error at runtime when it tries to create a new instance of the Location class on iOS:
TypeError: undefined is not a constructor (evaluating 'new nativescript_geolocation_1.Location()')

**Comment by ruslan-polutsygan** [comment]
Hello

Just got `nativescript_geolocation_1.Location is not a constructor` on Android

**Comment by dreamcatcher-studio** [comment]
Hi

I'm getting  "nativescript_geolocation_1.Location is not a constructor" on android when tried to use: let myLocation = new Location();

**Comment by MentalRender** [comment]
I get the same error when I tried to **getDistance()** with **[nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/location/basic-location-example/basic-location-example.ts)**....

Any idea?

**Comment by sserdyuk** [comment]
@MentalRender Here's my comment from the other now closed ticket.

> This issue stems from the fact that Location is defined in location.d.ts, but in reality is not exported by nativescript-geolocation module, so the following code compiles but fails at runtime.
> 
> `import { isEnabled, enableLocationRequest, getCurrentLocation, Location, distance } from "nativescript-geolocation";`
> 
> The solution is to import module that exports the class for real, which is nativescript-geolocation-common. The following code works correctly:
> 
> ```
> import { isEnabled, enableLocationRequest, getCurrentLocation, distance } from "nativescript-geolocation";
> import { Location } from "nativescript-geolocation/nativescript-geolocation-common";
> ```
> I don't know how such discrepancy between definition file and real code got into the release. Feel free to tag is a bug.

**Comment by DimitarTachev** [comment]
@MentalRender, thanks for investigating that.

The Location class is now exported by default and the issue is not reproducible anymore.
