### ISSUE TITLE
[Android] Enable Location 

### ISSUE THREAD

**Issue by andreacappadona17** [NativeScript/nativescript-geolocation#52]
Is there a way to enable geolocation, in a way similar to that of Google Maps in Android 7?
I ask this because when checking for location, if the user allowed it, and disabled it later, the user is not prompt the permission.

![screenshot_20170410-122442](https://cloud.githubusercontent.com/assets/19609031/24858712/bd44c4fe-1ded-11e7-86d4-5428a94cd3ec.png)
![screenshot_20170410-122525](https://cloud.githubusercontent.com/assets/19609031/24858713/bd68480c-1ded-11e7-9ab0-3aba86a78a09.png)

**Comment by DimitarTachev** [comment]
Hi @andreacappadona17 

Could you check the isEnabled method combined with the enableLocationRequest one once again and update us back? We fully replaced the old Android implementation with the Google Play Services one (used by Google Maps).

You could check the v4.0.0 release notes [here](https://github.com/NativeScript/nativescript-geolocation/releases/tag/v4.0.0).

**Comment by andreacappadona17** [comment]
Hi @DimitarTachev 

the new version rocks!

Thank you
