### ISSUE TITLE
Not working on version 2.5

### ISSUE THREAD

**Issue by d3mac123** [NativeScript/nativescript-geolocation#56]
I keep getting this info while installing:
npm WARN nativescript-geolocation@3.0.0 requires a peer of tns-core-modules@^3.0.0 || ^3.0.0-rc.1 || >=3.0.0-2017 but none was installed.

How to install it with 2.5?

**Comment by EddyVerbruggen** [comment]
That's because version 3.0.0 of this plugin is compatible with those peer dependencies you listed.

`npm show nativescript-geolocation@0.0.19` shows that 0.0.19 should work fine with your setup (NativeScript 2.5).

**Comment by d3mac123** [comment]
Thanks Eddy! I am new to NS and I was trying tns plugin add nativescript-geolocatio@2.5.0

**Comment by EddyVerbruggen** [comment]
No worries! It doesn't really help npm versions are hard to find. So you (and I) may want to remember that `npm show <packagename>` command to list 'em nicely 👍

**Comment by d3mac123** [comment]
You are the master!

Taking advantage, I am trying to get the current location (from my device or emulator) at start time (meaning the app will set an origin location when it is loaded) but, I am not sure I am doing it right (I have to admit I am still "fighting" with the concept of page.js and page-view-model.js). 

Sometimes I get the right info ("loc" from your sample code) but (especially on Android), most times I get a Error: Timeout while searching for location!

My question is, what's the best way to capture this info?
