### ISSUE TITLE
Crashing with version 3.0 on Android

### ISSUE THREAD

**Issue by d3mac123** [NativeScript/nativescript-geolocation#60]
The sample app below runs fine on iOS but crashes on Android. If I comment the watchId part, the app runs ok on Android, which confirms the issue is with the geolocation plugin. Can you please check? Thanks!

```

var observable = require("data/observable");
var pageModule = require("ui/page");
var viewModel = new observable.Observable();
var geolocation = require("nativescript-geolocation");
var view = require("ui/core/view");

var activeLoc = [];
var pilotList
var watchId

var drawer;
exports.pageLoaded = function(args) {
    page = args.object;
    drawer = view.getViewById(page, "sideDrawer");
    pilotList = view.getViewById(page, "pilotList");
    viewModel.set("activeList",activeLoc);
    page.bindingContext = viewModel;
}

exports.toggleDrawer = function() {
    drawer.toggleDrawerState();
};


//Update dashboard
function updateDash(args) {
    var lat = args.latitude;
    var lon = args.longitude;
    activeLoc.push({listLat:lat,listLon:lon})   
}
exports.updateDash = updateDash;

//starts dashboard
watchId = geolocation.watchLocation(
function (loc) {
    if (loc) {
      updateDash(loc)                
    }
}, 
function(e){
    console.log("Error: " + e.message);
},
{desiredAccuracy: 3, updateDistance: 10, maximumAge:5000}); 

```
The xml file:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"  xmlns:sd="nativescript-telerik-ui/sidedrawer" xmlns:x="nativescript-statusbar" backgroundSpanUnderStatusBar="true" class="page" actionBarHidden="false" loaded="pageLoaded">
    <Page.actionBar>
        <ActionBar title="Dashboard">
            <StackLayout orientation="horizontal"
                ios:horizontalAlignment="center"
                android:horizontalAlignment="left">
                <Image src="res://bf_logo" class="action-image"></Image>
            </StackLayout>
        </ActionBar>
    </Page.actionBar>

<x:StatusBar ios:barStyle="light" android:barStyle="#303030" />


    <sd:RadSideDrawer id="sideDrawer" drawerLocation="left">
        <!-- side drawer content -->
        <sd:RadSideDrawer.drawerContent>
            <StackLayout class="sidedrawer-left">

                <StackLayout class="sidedrawer-content">
                    <ListView id="pilotList" items="{{ activeList }}">
                        <ListView.itemTemplate>
                            <GridLayout columns="*,*2,*">
                                <Label text="{{ listLat }}" col="0"  class="listNick" />
                                
                            </GridLayout>
                        </ListView.itemTemplate>
                    </ListView>
                </StackLayout>
            </StackLayout>
        </sd:RadSideDrawer.drawerContent>
      
      
        <!-- The main content -->
        <sd:RadSideDrawer.mainContent>

                <!-- <GridLayout columns="*" rows="60,*,50,32" style.backgroundColor="#182126">  -->
                <GridLayout columns="*" rows="60,*,60" style.backgroundColor="#36283D">   

                    
                    <ContentView row="2" tap="toggleDrawer">
                        </ContentView>

                </GridLayout>

            </sd:RadSideDrawer.mainContent>
    </sd:RadSideDrawer>
</Page>
```

**Comment by PeterStaev** [comment]
Interesting, I'm using the `watchLocation` and at least in the android sims it is working w/o any problems. What error do you get when the app crashes?

**Comment by d3mac123** [comment]
This is what I get from the device:
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.test/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js, line: 149, column: 13

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.test/files/app/main-page.js', line: 80, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.test/files/app/main-page.js', line: 80, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js, line: 149, column: 13

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.test/files/app/main-page.js', line: 80, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6237)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    android.app.ActivityThread.-wrap11(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'enableLocationRequestCore', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 149, column: 14
	Frame: function:'watchLocation', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 168, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.test/files/app/main-page.js', line: 80, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 30, column: 31
	Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 95, column: 40
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 177, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 678, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.test/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 16, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
	at com.tns.Runtime.callJSMethod(Runtime.java:890)
	at com.tns.Runtime.callJSMethod(Runtime.java:874)
	at com.tns.Runtime.callJSMethod(Runtime.java:866)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
	at android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:453)
	... 19 more

**Comment by radeva** [comment]
Hi @d3mac123,

Recently we did some re-organisation of the plugin and the demos. Could you update the plugin and tell us if this is still an issue?

Best regards,
Veselina

P.S. In case no answer is received in 7 days, the issue will be closed.
