### ISSUE TITLE
Issue with creating new Location from code behind 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-geolocation#63]
When you try to create a new `Location` from code behind the following error will be throw:
```
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not a constructor (evaluating 'new nativescript_geolocation_1.Location()')
CONSOLE ERROR [native code]: ERROR CONTEXT [object Object]
```
The problem could be reproduced in this sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-geolocation/files/1055025/Archive.zip)

**Comment by isaacfi** [comment]
I have the same issue, can you provide a workaround? I believe that could be the native code related to the Location class, but I cannot call the native constructor and wrap into the nativescript object.

Regards

**Comment by sserdyuk** [comment]
@tsonevn @isaacfi  This issue stems from the fact that Location is defined in location.d.ts, but in reality is not exported by nativescript-geolocation module, so the following code compiles but fails at runtime.

`import { isEnabled, enableLocationRequest, getCurrentLocation, Location, distance } from "nativescript-geolocation";`

The solution is to import module that exports the class for real, which is nativescript-geolocation-common. The following code works correctly:

```
import { isEnabled, enableLocationRequest, getCurrentLocation, distance } from "nativescript-geolocation";
import { Location } from "nativescript-geolocation/nativescript-geolocation-common";
```
I don't know how such discrepancy between definition file and real code got into the release. Feel free to tag is a bug.

**Comment by tbozhikov** [comment]
Closing in favour of https://github.com/NativeScript/nativescript-geolocation/issues/50
