### ISSUE TITLE
Inaccurate

### ISSUE THREAD

**Issue by PerryRylance** [NativeScript/nativescript-geolocation#69]
I decided to do some real testing rather than emulated, and the results are woefully inaccurate. I walked around the block and found my location would stick for 10+ seconds sometimes, and half the time it showed me as being nowhere near the path I was on

**Comment by radeva** [comment]
Hi @PerryRylance ,

Thanks for reporting the issue. We'll need some more info to further investigate it:
 - Is this on Android or iOS 
 - which version of the operating system
 - what is the device which you use for these tests

Could you send us a sample app (as .zip or just refer to a repo) where we can take a look at the exact code?

Best regards,
Veselina

**Comment by PerryRylance** [comment]
Hi Veselina

This is on an Android, Samsung A5, Version 6.0

I've tried the following on page load

```
geolocation.watchLocation(
	updatePosition,
	function(e) {
		alert(e.message);
	},
	{
		desiredAccuracy: 0,
		updateDistance: 1,
		updateTime: 2000
	}
);
```

This doesn't work at all unless you put it in a timeout. Even then, it barely fires (maybe once every 2 minutes?)

I then tried this

```
setInterval(function() {
	geolocation.getCurrentLocation({ updateDistance: 0.1, maximumAge: 5000, timeout: 20000 }).then(updatePosition);
}, 2000);
```

But the results are so inaccurate it's practically useless for my project

**Comment by radeva** [comment]
Hi @PerryRylance ,

Could you try to do the following import:
`import { Accuracy } from "ui/enums";`
and use `Accuracy.high` as a value of desiredAccuracy in your first code sample? 

`desiredAccuracy: 0` sets Android accuracy to ACCURACY_COARSE which gives approximate accuracy. 
Setting plugin's `desiredAccuracy` to `Accuracy.high` will set the Android accuracy to ACCURACY_FINE which gives finer location accuracy.

I hope this helps.

Best regards,
Veselina

**Comment by PerryRylance** [comment]
Hi @radeva 

I required enums and used enums.Accuracy.high (which I can confirm evaluates to 3) however this made no difference at all with either watchLocation or getCurrentLocation

Sorry to be the bearer of bad news!

**Comment by DimitarTachev** [comment]
Hi @PerryRylance,

Could you check the accuracy again and update us back? We fully replaced the old Android implementation with the Google Play Services one (used by Google Maps).

You could check the v4.0.0 release notes [here](https://github.com/NativeScript/nativescript-geolocation/releases/tag/v4.0.0).
