### ISSUE TITLE
enableLocationRequest does not return on enabling or denying

### ISSUE THREAD

**Issue by h43z** [NativeScript/nativescript-geolocation#71]
It does resolve if location is already enabled.

But it does neither reject if location permission is denied or resolve if permission was granted and location was enabled.

Or am I doing something wrong?

```
geolocation.enableLocationRequest()
  .then(resolved => {
    console.log('resolved')
  })
  .catch(rejected =>{
    console.log('rejected')
  })
```

**Comment by davidpronk** [comment]
https://github.com/NativeScript/nativescript-geolocation/issues/37

**Comment by radeva** [comment]
Closing the issue since it's duplicate of #37

**Comment by h43z** [comment]
the please reopen #37

**Comment by h43z** [comment]
#37 does not work for me (I can only test Android).
Can one of the issues be reopened?

**Comment by ickata** [comment]
I confirm that `enableLocationRequest` promise is never resolved on Android. I am testing on 7.1 emulator. 

```
      geolocation.enableLocationRequest().then( function () {
         // I never get here...
      });
```

**Comment by ickata** [comment]
@radeva I'm not sure if GitHub sends notifications for comments in closed issues, therefore I tag you...

**Comment by radeva** [comment]
Hi @ickata 

Could you open a new issue using the issue template? You can also link this one and #37 there.

Thanks!

**Comment by ickata** [comment]
#91
