### ISSUE TITLE
Different behaviour for getCurrentLocation

### ISSUE THREAD

**Issue by surdu** [NativeScript/nativescript-geolocation#78]
When you call `getCurrentLocation` from a cold start, usually the location is very old (several minutes). This in turn will cause `getCurrentLocation` to fail every time if you specify `maximumAge` to something like 10 seconds.

What I propose is to change the behaviour of `getCurrentLocation` like this:

Attempt to retrieve the location as it is today. Check if the timestamp of location <= maximumAge. If the check fails, retry location fetching until timeout or timestamp is ok.

**Comment by DimitarTachev** [comment]
Hi @surdu, 

Thanks for the feedback!

This sounds like a very nice improvement. I've labeled it with 'help wanted' and 'good first issue' as someone from the community could open a pull request before we get to it.

**Comment by sm1ddy** [comment]
Same issue here, basically breaks the whole plugin.

Has anyone had a try at implementing the above logic?

**Comment by surdu** [comment]
Was this successfully fixed in #96 ?

**Comment by DimitarTachev** [comment]
Fixed and released
