### ISSUE TITLE
ios Error: New location is older than requested maximum age!

### ISSUE THREAD

**Issue by nmongiya** [NativeScript/nativescript-geolocation#79]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS 11.0.2
- Device. iPhone 6?

### Please, provide the following version numbers that your issue occurs with:

"nativescript-pro-ui": "^3.1.3",
tns --version 3.2.0
"tns-ios": {
      "version": "3.2.0"
    }

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

`geolocation.isEnabled()
			.then((hasPermission) => {
				if (hasPermission) {
					this.getLocation();
				} else {
					geolocation.enableLocationRequest()
						.then(() => {
							this.getLocation();
						})
				}

			})
			.catch(() => {
				geolocation.enableLocationRequest()
					.then(() => {
						this.getLocation();
					})
			});`

**Comment by DimitarTachev** [comment]
Hi @nmongiya, 

What's the content of your "this.getLocation();" method?

**Comment by nmongiya** [comment]
Hi @DimitarTachev 
`getLocation() {
		geolocation.getCurrentLocation({ desiredAccuracy: Accuracy.high, maximumAge: 5000, timeout: 20000 })
			.then((location) => {
				console.log('location received' + location);
			})
			.catch((error) => {
				console.log('error received' + error);
			});
	}`

**Comment by DimitarTachev** [comment]
@nmongiya I suppose you found the same behavior as issue #78. You could try the workaround suggested there till someone implement the logic inside the plugin.

**Comment by sm1ddy** [comment]
@DimitarTachev, I think this issue is quite serious. I'm finding that it completely breaks nativescript-geolocation on newer devices.

Might try to have a look at the plugin myself, would be good to see if anyone else is working on it.

Thanks for the great plugin btw!

**Comment by DimitarTachev** [comment]
Hi @sm1ddy, thanks for your feedback.

Unfortunately, the fix described in issue #78 is still on our TODO list. It will be great if you are able to implement it in the plugin.

**Comment by DimitarTachev** [comment]
Fixed and released
