### ISSUE TITLE
Build failed on Android after upgrade the plugin

### ISSUE THREAD

**Issue by OPADA-Eng** [NativeScript/nativescript-geolocation#80]
Hi, after I added the new version of the plugin the project can't be build any more and stop in the middle of the building process.
However I cloned the demo and build it also on my machine and got this errors:
`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-geolocation", relative to: app/tns_modules/
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-geolocatio`

### Which platform(s) does your issue occur on?
Android
my project running with:
### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 4.6.1
- **CLI:** 3.2.0
- **Cross-platform modules:** 3.2.0
- **Runtime(s):** tns-android": 3.2.0
- **Enviroment**: Ubuntu 16.04

in my project I'm getting this build error: 

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForF0F1F2F3F4F5F6F7F8F9F10F11F12F13F14F15F16F17F18Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 65758 into a non-jumbo instruction!
`

**Comment by DimitarTachev** [comment]
Hi @OPADA-Eng,

Do you use the plugin from NPM or directly from this repository?

Here are some possible reasons for getting this exception:
1) The typescript files in the src folder are not compiled to javascript files. This is possible if you are using the plugin directly from this repository instead of the published NPM package - run the _npm run build_ command in the src folder before running the demo.
2) Wrong files in the _node_modules_ or _platforms_ folders in your app - try deleting both of the folders, double check that the plugin is specified as a dependency in your package.json and run the app again.

**Comment by OPADA-Eng** [comment]
I cloned this repo to my pc and navigated to demo folder 
then I run the demo using 
`tns run android `

**Comment by OPADA-Eng** [comment]
After search I found this solution:
I put this code in my **app.gradle** under **App_Resources** folder:
`dexOptions {
    jumboMode = true
}`

and that resolved the problem
Thanks
