### ISSUE TITLE
Incompatibility with nativescript-plugin-firebase

### ISSUE THREAD

**Issue by hettiger** [NativeScript/nativescript-geolocation#81]
There's a version conflict between nativescript-geolocation and nativescript-plugin-firebase.

As of

https://github.com/NativeScript/nativescript-geolocation/blob/d47fc8dc45ceffa3c2a39b8c48d3099937a1e414/src/platforms/android/include.gradle#L19

nativescript-geolocation wants Google Play Services 11.4.0 but [nativescript-plugin-firebase forces me to pin to version 11.2.2](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#includegradle-failed-to-apply-plugin--for-input-string-).

Is version 11.4.0 actually really required for this plugin to work or can you just pin to 11.2.2 as well? I think this is a issue for many people because nativescript-plugin-firebase is quite an important plugin... If not, what could I do about it? I really would like to be able using both of these plugins together in one app.

Here's the original error message I get after installing the nativescript-geolocation plugin and trying to build for Android.

>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':processF0F1F2F3F4F5F6F7DebugGoogleServices'.
>> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.4.0.

>>>

**Comment by hettiger** [comment]
I can confirm that enableLocationRequest does work using 11.2.2. I forked this repo and repackaged the plugin with a pinned version of 11.2.2 as a workaround which does work for me so far.

**Comment by DimitarTachev** [comment]
Hi @hettiger,

Thanks for reporting this incompatibility.

The firebase plugin supports a custom Google Play Services version. Check [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#includegradle-failed-to-apply-plugin--for-input-string-).

In other words, you could set:
```
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "11.4.0"
  }
}
```
in your _app/App_Resources/Android/app.gradle_.

We should introduce the same flexible version support in the next version of the geolocation plugin. It should be the same as the one [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/include.gradle) combined with the README section.

If the firebase plugin is not OK with the 11.4.0 version, and you try the above-mentioned approach in your geolocation fork allowing you to set the _googlePlayServicesVersion_ property to 11.2.2, a pull request will be highly appreciated.

**Comment by hettiger** [comment]
@DimitarTachev Thank you, I've opened a Pull Request. (nativescript-plugin-firebase is not compatible with 11.4.0)

**Comment by jlooper** [comment]
This contribution has earned a badge of distinction! Well done!

![contrib](https://user-images.githubusercontent.com/1450004/31724410-9742e996-b3ef-11e7-9b4a-9917d9f00b03.png)

**Comment by hettiger** [comment]
Than you @jlooper very mich appreciate it :-)

**Comment by DimitarTachev** [comment]
@hettiger The changes were published and available in [v4.2.0](https://github.com/NativeScript/nativescript-geolocation/releases/tag/v4.2.0)

**Comment by DragoTechInnovations** [comment]
Hi I am having the same problem. But no matter what version I select it gives me an error to update to that version (which it is already on). How can I solve that?

**Comment by DragoTechInnovations** [comment]
I did something else. I force changed the version from `include.gradle` in geolocation. That solved the problem. Probably not the best way but it works now.

**Comment by hettiger** [comment]
@DragoTechInnovations This should not be necessary but if it doesn't bother you that's fine to me.

**Comment by hettiger** [comment]
@DragoTechInnovations I've just upgraded my app to {NS} 4. I had the same error too. The fix was as simple as following these instructions: https://github.com/EddyVerbruggen/nativescript-plugin-firebase#includegradle-failed-to-apply-plugin--for-input-string-

"nativescript-plugin-firebase": "^5.3.0", requires you to set something like this.

```
  project.ext {
    googlePlayServicesVersion = "12.0.1"
    supportVersion = "26.0.0"
  }
```

`nativescript-geolocation` will pick up that version too and work just fine. Give it a try. It's a much better approach than modifying node_modules contents.

**Comment by lin-brian-l** [comment]
I've been having the same problem and @hettiger's solution helped me resolve the version conflict error, but I then ran into this error:

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0) from [com.android.support:design:26.0.0] AndroidManifest.xml:28:13-35
        is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```

As per [this SO post](https://stackoverflow.com/questions/45553058/android-manifest-merger-failed-gms-play-services-firebase?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), I changed my `supportVersion` in `project.ext` from `26.0.0` => `26.1.0` and it worked.
