### ISSUE TITLE
App always crash on geolocation enabled check

### ISSUE THREAD

**Issue by TheOnlyMatt** [NativeScript/nativescript-geolocation#90]
### Make sure to check the demo app(s) for sample usage 
Working with Nativescript Playground

### Which platform(s) does your issue occur on?
Tested on an Android device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime: 3.3.0
- Plugin: 4.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 
I cannot use any method belonging to the plugin.
I have created a location service, checking in the constructor, if the geolocation is enabled on the device, app is crashing throwing a big exception : 
An uncaught exception occurred on "GoogleApiHandler" thread.
java.lang.NoSuchMethodError: No virtual method zzajj()V in class Lcom/google/android/gms/common/internal/zzd; or its super classes (declaration of 'com.google.android.gms.common.internal.zzd' appears in /data/app/myapp/base.apk) 
at
com.google.android.gms.internal.zzbzu.zza(Unknown Source) etc ...

This error is also happening if I put it right into a component.

### Is there any code involved? 

import * as geolocation from "nativescript-geolocation";

@Injectable()

export class Location {
    onLocationChange: Subject<any> = new Subject<any>();

    private _location : any
    private _located : boolean = false

    constructor(){
        let self = this

        console.log("in constructor")
        geolocation.isEnabled().then(function (isEnabled) {
            console.log("then")
            if (!isEnabled) {
                console.log("location not enabled")
                geolocation.enableLocationRequest().then(function () {
                    console.log("after enable location request")
                }, function (e) {
                    console.log("Error: " + (e.message || e));
                });
            }
            else
                console.log("location enabled")
        }, function (e) {
            console.log("Error: " + (e.message || e));
        });

    }

When running the app, I only get the "in constructor" log before the crash.
If I remove this snippet, there is no more error.

Obviously, as it cannot be check if the location is enabled, it's also impossible to get the location data.

Does anybody have an idea why this is happening ?
Thanks

**Comment by OPADA-Eng** [comment]
@TheOnlyMatt isEnabled() became promise wise function as they said in the crushing changes in v4
you can use it as promise and that will resolve the issue.

**Comment by TheOnlyMatt** [comment]
Hello, 
That's the point, I think using isEnabled() as a promise.
After calling isEnabled(), the then() statement is used and sets the returned value in the isEnabled variable. When something is returned by the function, it should log "then" and then do the other stuff. However, even this log isn't shown.
Moreover this is the code straight from the [angular demo](https://github.com/NativeScript/nativescript-geolocation/blob/master/demo/app/main-page.ts) so it is supposed to be working and in the worst case log the error message, but it just crashes.

Am I wrong about this ?

**Comment by zbranzov** [comment]
Hi @TheOnlyMatt,
Using the code from your constructor I wasn't able to reproduce the abovementioned error. All console logs were properly displayed. Can you share a complete example if you haven't already resolved the case?

**Comment by TheOnlyMatt** [comment]
Yeah thank you I just solved it, by changing the Google Play Services version in node_modules/nativescript-geolocation/platforms/android/include.gradle (set it to 11.2.+).
There were a conflict with the Gmaps plugin.

**Comment by DimitarTachev** [comment]
@TheOnlyMatt, the Google Play Services version of both plugins is configurable by a project property without any code changes in node_modules. Take a look at the [version conflicts section of the README](https://github.com/NativeScript/nativescript-geolocation#version-conflicts--google-play-services) for more details.

**Comment by NickIliev** [comment]
@TheOnlyMatt, @DimitarTachev  at this very moment there is a known bug in tns-android 3.3.0 which is causing any properties set in the `app.gradle` (like `googlePlayServicesVersion `) not to be respected. 

The bug is logged [here](https://github.com/NativeScript/android-runtime/issues/878) and currently our runtime team is working on a fix. Meanwhile as a solution use in-android 3.2.0

**Comment by tahir-jamil** [comment]
i am getting this error again what can i do?

**Comment by leocrawf** [comment]
same issue here

**Comment by chimmelb** [comment]
I just updated to NS8, and ran into this old bug. Looking into the Gradle changes as mentioned by nicklliev.
