### ISSUE TITLE
This app won’t run unless you update google play services

### ISSUE THREAD

**Issue by guestisp** [NativeScript/nativescript-geolocation#95]
i’ve added nativescript-geolocation plugin but i’m unable to use it (API Level 17) because i’m getting the error `This app won't run unless you update google play services`

I’ve tried to force a specific google play service version in `App_Resources/Android/app.gradle`:

```
compile 'com.google.android.gms:play-services-location:11.0.4'
```

but this won’t solve the issue. How can I update google app services on the emulator ? I thought that gradle would update it automatically… (i’m using an emulator image with Google API)

I can't upgrade to a newer API level because i have to support Android 4.2

**Comment by DimitarTachev** [comment]
Hi @guestisp,

You could take a look at [this thread](https://stackoverflow.com/questions/35476182/updating-google-play-services-in-emulator) explaining the Play Services update procedure on emulators. I was able to update my Play Services version using the [Android Studio 3.0](https://developer.android.com/studio/index.html) emulators as they have the Play Store included and you could update any app (including the Google Play Services one) just like on a real device.

As far as I know, you will be able to update to the latest Google Play Services version even on Android 4.2 (the latest required API level in [their docs is 14 for Play Service 10.2+](https://developers.google.com/android/guides/releases#february_2017_-_version_102)).

**Comment by guestisp** [comment]
Already saw that thread.
Play Store is only available on latest images, not for 4.2. When using images with 4.2 (with Google APIs), play services can't be ugraded because market is missing and I can't access the market via browser because the stock browser is deprecated and not supported anymore by the market site

**Comment by tsonevn** [comment]
Hi @guestisp,
Were you able to resolve your case or you still facing an issue with updating the Google play services on an emulator?
You could also review this thread in [StackOverflow](https://stackoverflow.com/a/44614237/6133327).

Hope this helps.

**Comment by guestisp** [comment]
I'm still facing the update issue
As workaround I've updated to a newer Android version, hitting another issue with this plugin

As wrote previously, I already saw that thread but play store is only available on recent images.
I absolutely need Android 4.2.2

**Comment by NickIliev** [comment]
closing the issue as it is not related to the nativescript-geolocation plugin but to the used version of emulator images. To use Google location we need a real device or emulator with installed Google Play.

**Comment by AnasSafi** [comment]
My solution for this problem in this link:

https://stackoverflow.com/a/57421675/2877427
