### ISSUE TITLE
Does this plugin work in China?

### ISSUE THREAD

**Issue by ludcila** [NativeScript/nativescript-geolocation#99]
I realize this might not be the best place to post this question, but since I am not getting any answers in the Nativescript forum, I will post it here.

Could anyone tell me whether the latest versions (4+) of the plugin work in China, given that it now relies on Google Play Services?

**Comment by lini** [comment]
The latest version of the plugin will not work if the Android device does not have Google Play Services.

**Comment by ludcila** [comment]
Are there any plans to support both Google Play Services and the Android Location Manager? As far as I know, phones in China don't have Google Play Store / Services pre-installed (and might not be straightforward for the users to install it on their own). I am not sure this dependency on Google is a good idea.

Would you consider allowing to switch programmatically between the new implementation using Google Play Services and the old one using Android Location Manager?

**Comment by lini** [comment]
There are no plans to offer such functionality in the plugin. If you must use LocationManager you should either use an older version of the plugin (v3.x.x) or you can submit a pull request that makes the plugin configurable and allows changing the location provider for Android.
